### PR TITLE
Add an option to raise the currently selected window in the window sw…

### PR DESCRIPTION
**Pull request by nikil**
This is my first attempt at modifying a gnome shell extension, so lemme know if I messed anything up!

### CODE REVIEW

**Comment by Leleat** [comment]
Code looks good to me. Only issue I have is with the wording. You don't 'raise' windows, you activate them. That means the window receive focus and you potentially change workspaces to it. If that behavior is intentional, I think the wording needs to be updated to reflect that. That said, I don't believe 'activate' is commonly used by users, is it? So I'd probably go with 'focus'. While not absolutely correct, I'd say it's more known.

**Comment by nikil** [comment]
Thanks for the feedback, I agree that 'focus' is probably the best term.  I updated the commit.

One question - once this PR is merged, how do my changes make it to extensions.gnome.org?

**Comment by Leleat** [comment]
Thanks for the MR!

> One question - once this PR is merged, how do my changes make it to extensions.gnome.org?

I need to upload a new version to the website (manually).

**Comment by Leleat** [comment]
> I need to upload a new version to the website (manually).

Which I've just done. So once the new version is reviewed by the EGO team, you can find it there.

**Pull request merged**
